import { ENV_ICON } from "@/assets/styles/picUrl";

export const Constant = {
  locName: '重庆',                    // 地址
  commonBorderColor: '#f1f1f1',      // 边框
  defaultBgColor: '#f4f4f4',         // 页面背景色
  CommonColor: {                     // 公共颜色
    default: '#8a8a8a',
    success: '#288d65',
    danger: '#c71622',
    primary: '#639be7'
  },
  messageCount: '9',                 // 未读消息
  home_category_arr: [               // 首页分类
    { url: ENV_ICON.icon_sf, text: '司法拍卖' },
    { url: ENV_ICON.icon_zc, text: '资产拍卖' },
    { url: ENV_ICON.icon_es, text: '二手房源' },
    { url: ENV_ICON.icon_jjr, text: '置业经理' },
    { url: ENV_ICON.icon_pg, text: '评估服务' },
  ],
  home_tab_arr: [                    // 首页tab
    { id: '1', val: '资产拍卖' },
    { id: '2', val: '司法拍卖' },
    { id: '3', val: '二手房' },
  ],
  account_category_arr: [ // 我的
    { id: '0', icon_url: ENV_ICON.icon_zl, title: '我的资料' },
    { id: '1', icon_url: ENV_ICON.icon_tj, title: '我的推荐' },
    { id: '2', icon_url: ENV_ICON.icon_cj, title: '我的成交' },
    { id: '3', icon_url: ENV_ICON.icon_card, title: '我的银行卡' },
    { id: '4', icon_url: ENV_ICON.icon_sy, title: '我的收益' },
    { id: '5', icon_url: ENV_ICON.icon_kefu, title: '联系客服' }
  ],
  collection_tab_arr: [ // 收藏
    { id: '0', val: '资产拍卖' },
    { id: '1', val: '司法拍卖' },
    { id: '2', val: '二手房' },
  ],
  recommend_tab_arr: [ // 我的推荐
    { id: '0', val: '客源' },
    { id: '1', val: '房源' },
  ],
  assetAuction_tab_arr: [ // 司法拍卖，资产拍卖
    { id: '0', val: '区域' },
    { id: '1', val: '价格' },
    { id: '2', val: '拍卖状态' },
    { id: '3', val: '拍卖时间' },
  ],
  recommend_area_arr: [
    { DicCode: 0, DicName: '小于60㎡', AreaMin: 0, AreaMax: 60 },
    { DicCode: 1, DicName: '60-80㎡', AreaMin: 60, AreaMax: 80 },
    { DicCode: 2, DicName: '80-100㎡', AreaMin: 80, AreaMax: 100 },
    { DicCode: 3, DicName: '100-120㎡', AreaMin: 100, AreaMax: 120 },
    { DicCode: 4, DicName: '120-140㎡', AreaMin: 120, AreaMax: 140 },
    { DicCode: 5, DicName: '140㎡以上', AreaMin: 140, AreaMax: undefined },
  ],
  houseTypeArr: [ // 户型多选框的数据源
    { DicName: '一室', DicCode: 1, select: false, id: 0 },
    { DicName: '二室', DicCode: 2, select: false, id: 1 },
    { DicName: '三室', DicCode: 3, select: false, id: 2 },
    { DicName: '四室', DicCode: 4, select: false, id: 3 },
    { DicName: '五室', DicCode: 5, select: false, id: 4 },
    { DicName: '五室以上', DicCode: 6, select: false, id: 5 },
  ],
  FloorDic: [ // 楼层
    { DicName: '1层', DicCode: 1 },
    { DicName: '2层', DicCode: 2 },
    { DicName: '3层', DicCode: 3 },
    { DicName: '4层', DicCode: 4 },
    { DicName: '5层', DicCode: 5 },
    { DicName: '6层', DicCode: 6 },
    { DicName: '7层', DicCode: 7 },
    { DicName: '8层', DicCode: 8 },
    { DicName: '9层', DicCode: 9 },
    { DicName: '10层', DicCode: 10 },
    { DicName: '11层', DicCode: 11 },
    { DicName: '12层', DicCode: 12 },
    { DicName: '13层', DicCode: 13 },
    { DicName: '14层', DicCode: 14 },
    { DicName: '15层', DicCode: 15 },
    { DicName: '16层', DicCode: 16 },
    { DicName: '17层', DicCode: 17 },
    { DicName: '18层', DicCode: 18 },
    { DicName: '19层', DicCode: 19 },
    { DicName: '20层', DicCode: 20 },
    { DicName: '21层', DicCode: 21 },
    { DicName: '22层', DicCode: 22 },
    { DicName: '23层', DicCode: 23 },
    { DicName: '24层', DicCode: 24 },
    { DicName: '25层', DicCode: 25 },
    { DicName: '26层', DicCode: 26 },
    { DicName: '27层', DicCode: 27 },
    { DicName: '28层', DicCode: 28 },
    { DicName: '29层', DicCode: 29 },
    { DicName: '30层', DicCode: 30 },
    { DicName: '31层', DicCode: 31 },
    { DicName: '32层', DicCode: 32 },
    { DicName: '33层', DicCode: 33 },
    { DicName: '34层', DicCode: 34 },
    { DicName: '35层', DicCode: 35 },
    { DicName: '36层', DicCode: 36 },
    { DicName: '37层', DicCode: 37 },
    { DicName: '38层', DicCode: 38 },
    { DicName: '39层', DicCode: 39 },
    { DicName: '40层', DicCode: 40 },
    { DicName: '41层', DicCode: 41 },
    { DicName: '42层', DicCode: 42 },
    { DicName: '43层', DicCode: 43 },
    { DicName: '44层', DicCode: 44 },
    { DicName: '45层', DicCode: 45 },
    { DicName: '46层', DicCode: 46 },
    { DicName: '47层', DicCode: 47 },
    { DicName: '48层', DicCode: 48 },
    { DicName: '49层', DicCode: 49 },
    { DicName: '50层', DicCode: 50 }
  ],
  auctionPriceArr: [ // 价格多选框的数据源
    { DicName: '40万以下', DicCode: 0, MinPrice: 0, MaxPrice: 400000, select: false, id: 0 },
    { DicName: '40-60万', DicCode: 1, MinPrice: 400000, MaxPrice: 600000, select: false, id: 1 },
    { DicName: '60-80万', DicCode: 2, MinPrice: 600000, MaxPrice: 800000, select: false, id: 2 },
    { DicName: '80-100万', DicCode: 3, MinPrice: 800000, MaxPrice: 1000000, select: false, id: 3 },
    { DicName: '100-150万', DicCode: 4, MinPrice: 1000000, MaxPrice: 1500000, select: false, id: 4 },
    { DicName: '150-200万', DicCode: 5, MinPrice: 1500000, MaxPrice: 2000000, select: false, id: 5 },
    { DicName: '200万以上', DicCode: 6, MinPrice: 2000000, MaxPrice: 100000000, select: false, id: 6 },
  ],
}