export const ENV_ICON = {
  icon_footer_home: require('@/assets/images/icon/icon_footer_home.png'),
  icon_footer_home_red: require('@/assets/images/icon/icon_footer_home_red.png'),
  icon_footer_recommend: require('@/assets/images/icon/icon_footer_recommend.png'),
  icon_footer_recommend_red: require('@/assets/images/icon/icon_footer_recommend_red.png'),
  icon_footer_collect: require('@/assets/images/icon/icon_footer_collect.png'),
  icon_footer_collect_red: require('@/assets/images/icon/icon_footer_collect_red.png'),
  icon_footer_user: require('@/assets/images/icon/icon_footer_user.png'),
  icon_footer_user_red: require('@/assets/images/icon/icon_footer_user_red.png'),
  icon_top_left: require('@/assets/images/icon/icon_top_left.png'),
  icon_top_screen: require("@/assets/images/icon/icon_top_screen.png"),
  icon_top_search: require('@/assets/images/icon/icon_top_search.png'),
  icon_off: require('@/assets/images/icon/icon_off.png'),
  icon_top_off: require('@/assets/images/icon/icon_top_off.png'),
}